exhaust_test: false


# ModelParams
scene_type: "DriveXWaymo"
resolution_scales: [1, 2, 4, 8, 16]
cam_num: 3
eval: false
num_pts: 600000
t_init: 0.1

start_time: 0
end_time: 85


order: 3 # new, 3 for cubic bezier
bbox_frame_interval: 6 # 3 frames for bbox

load_sky_mask: true
load_dynamic_mask: true
load_bbox_mask: true

# PipelineParams

# OptimizationParams
iterations: 30000

opacity_lr: 0.005

densify_until_iter: 15000
densify_grad_threshold: 0.00017
sh_increase_interval: 2000


prune_interval: 200

render_type: bezier

static_thresh: 1.0

thresh_opa_prune: 0.005
opa_init: 0.01
